AUT=addressbook
ENVVARS=envvars
HOOK_SUB_PROCESSES=false
IMPLICITAUTSTART=0
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_case1 tst_case2 tst_case3 tst_AUT_crash_scr_built_1900 tst_debug_version_app tst_manage_contacts tst_test tst_test_1 tst_builtin_hook tst_case3,tst_add_new_person tst_QML_partial_visibility_check tst_case4 tst_qt_quick_engine tst_insert_comment
VERSION=3
WRAPPERS=Qt
