# AddressBook Page Object Definitions
# encoding: UTF-8
# Generated from: snapshot_main.xml
# Generated by: Squish MCP POM Generator

from objectmaphelper import *

Address_Book_QMainWindowLayout = {"object_name": "_layout", "type": "QMainWindowLayout", "unnamed": 1, "visible": True}
Address_Book_QTableWidget = {"type": "QTableWidget", "unnamed": 1, "visible": True}
Address_Book_QToolBarExtension = {"object_name": "qt_toolbar_ext_button", "type": "QToolBarExtension", "unnamed": 1, "visible": False}
Address_Book_QToolBarExtension_2 = {"object_name": "qt_toolbar_ext_button", "occurrence": 2, "type": "QToolBarExtension", "unnamed": 1, "visible": False}
Address_Book_QToolButton = {"object_name": "qt_menubar_ext_button", "type": "QToolButton", "unnamed": 1, "visible": False}
Address_Book_QWidget = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_hcontainer", "type": "QWidget", "unnamed": 1, "visible": False}
Address_Book_QWidget_2 = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_vcontainer", "type": "QWidget", "unnamed": 1, "visible": False}
Address_Book_QWidget_2_2 = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_hcontainer", "occurrence": 2, "type": "QWidget", "unnamed": 1, "visible": False}
Address_Book_QWidget_2_3 = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_vcontainer", "occurrence": 2, "type": "QWidget", "unnamed": 1, "visible": False}
Address_Book_QWidget_3 = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_hcontainer", "occurrence": 3, "type": "QWidget", "unnamed": 1, "visible": False}
Address_Book_QWidget_3_2 = {"container": Address_Book_QTableWidget, "object_name": "qt_scrollarea_vcontainer", "occurrence": 3, "type": "QWidget", "unnamed": 1, "visible": False}