# encoding: UTF-8

from objectmaphelper import *

address_Book_MainWindow = {"type": "MainWindow", "unnamed": 1, "visible": 1, "windowTitle": "Address Book"}
address_Book_File_QToolBar = {"type": "QToolBar", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow, "windowTitle": "File"}
address_Book_File_QTableWidget = {"aboveWidget": address_Book_File_QToolBar, "type": "QTableWidget", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}
address_Book_QMenuBar = {"type": "QMenuBar", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}
address_Book_File_QMenu = {"title": "File", "type": "QMenu", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}
qFileDialog_QFileDialog = {"name": "QFileDialog", "type": "QFileDialog", "visible": 1}
qFileDialog_splitter_QSplitter = {"name": "splitter", "type": "QSplitter", "visible": 1, "window": qFileDialog_QFileDialog}
splitter_frame_QFrame = {"container": qFileDialog_splitter_QSplitter, "name": "frame", "type": "QFrame", "visible": 1}
frame_stackedWidget_QStackedWidget = {"container": splitter_frame_QFrame, "name": "stackedWidget", "type": "QStackedWidget", "visible": 1}
stackedWidget_treeView_QTreeView = {"container": frame_stackedWidget_QStackedWidget, "name": "treeView", "type": "QTreeView", "visible": 1}
treeView_QScrollBar = {"container": stackedWidget_treeView_QTreeView, "type": "QScrollBar", "unnamed": 1, "visible": 1}
qFileDialog_Open_QPushButton = {"text": "Open", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": qFileDialog_QFileDialog}
address_Book_MyAddresses_adr_MainWindow = {"type": "MainWindow", "unnamed": 1, "visible": 1, "windowTitle": "Address Book - MyAddresses.adr"}
address_Book_MyAddresses_adr_File_QToolBar = {"type": "QToolBar", "unnamed": 1, "visible": 1, "window": address_Book_MyAddresses_adr_MainWindow, "windowTitle": "File"}
address_Book_MyAddresses_adr_File_QTableWidget = {"aboveWidget": address_Book_MyAddresses_adr_File_QToolBar, "type": "QTableWidget", "unnamed": 1, "visible": 1, "window": address_Book_MyAddresses_adr_MainWindow}
file_QHeaderView = {"container": address_Book_MyAddresses_adr_File_QTableWidget, "orientation": 2, "type": "QHeaderView", "unnamed": 1, "visible": 1}
o1_HeaderViewItem = {"container": file_QHeaderView, "text": 1, "type": "HeaderViewItem", "visible": True}
o6_HeaderViewItem = {"container": file_QHeaderView, "text": 6, "type": "HeaderViewItem", "visible": True}
address_Book_MyAddresses_adr_Remove_QToolButton = {"text": "Remove", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_MyAddresses_adr_MainWindow}
address_Book_Delete_QMessageBox = {"type": "QMessageBox", "unnamed": 1, "visible": 1, "windowTitle": "Address Book - Delete"}
address_Book_Delete_No_QPushButton = {"text": "No", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": address_Book_Delete_QMessageBox}
address_Book_Delete_Yes_QPushButton = {"text": "Yes", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": address_Book_Delete_QMessageBox}
address_Book_QMessageBox = {"type": "QMessageBox", "unnamed": 1, "visible": 1, "windowTitle": "Address Book"}
address_Book_No_QPushButton = {"text": "No", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": address_Book_QMessageBox}
address_Book_Unnamed_MainWindow = {"type": "MainWindow", "unnamed": 1, "visible": 1, "windowTitle": "Address Book - Unnamed"}
address_Book_Unnamed_Add_QToolButton = {"text": "Add", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
address_Book_Add_Dialog = {"type": "Dialog", "unnamed": 1, "visible": 1, "windowTitle": "Address Book - Add"}
address_Book_Add_Forename_QLabel = {"text": "Forename:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
forename_LineEdit = {"buddy": address_Book_Add_Forename_QLabel, "type": "LineEdit", "unnamed": 1, "visible": 1}
address_Book_Add_Surname_QLabel = {"text": "Surname:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
surname_LineEdit = {"buddy": address_Book_Add_Surname_QLabel, "type": "LineEdit", "unnamed": 1, "visible": 1}
address_Book_Add_Email_QLabel = {"text": "Email:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
email_LineEdit = {"buddy": address_Book_Add_Email_QLabel, "type": "LineEdit", "unnamed": 1, "visible": 1}
address_Book_Add_Phone_QLabel = {"text": "Phone:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
phone_LineEdit = {"buddy": address_Book_Add_Phone_QLabel, "type": "LineEdit", "unnamed": 1, "visible": 1}
address_Book_Add_OK_QPushButton = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
address_Book_Help_QMenu = {"title": "Help", "type": "QMenu", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}
address_Book_New_QToolButton = {"text": "New", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}

address_Book_Unnamed_File_QToolBar = {"type": "QToolBar", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow, "windowTitle": "File"}
address_Book_Unnamed_File_QTableWidget = {"aboveWidget": address_Book_Unnamed_File_QToolBar, "type": "QTableWidget", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
file_QHeaderView_2 = {"container": address_Book_Unnamed_File_QTableWidget, "orientation": 1, "type": "QHeaderView", "unnamed": 1, "visible": 1}
splitter_sidebar_QSidebar = {"container": qFileDialog_splitter_QSplitter, "name": "sidebar", "type": "QSidebar", "visible": 1}
qFileDialog_backButton_QToolButton = {"name": "backButton", "type": "QToolButton", "visible": 1, "window": qFileDialog_QFileDialog}
address_Book_Add_QToolButton = {"text": "Add", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_MainWindow}
address_Book_Add_Cancel_QPushButton = {"text": "Cancel", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": address_Book_Add_Dialog}
file_QHeaderView_3 = {"container": address_Book_File_QTableWidget, "orientation": 1, "type": "QHeaderView", "unnamed": 1, "visible": 1}
address_Book_Unnamed_New_QToolButton = {"text": "New", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
o_QQuickWindowQmlImpl = {"type": "QQuickWindowQmlImpl", "unnamed": 1, "visible": True}
waterText_Text = {"container": o_QQuickWindowQmlImpl, "objectName": "waterText", "type": "Text", "visible": True}
stateText_Text = {"container": o_QQuickWindowQmlImpl, "objectName": "stateText", "type": "Text", "visible": True}
washerType_Text = {"container": o_QQuickWindowQmlImpl, "objectName": "washerType", "type": "Text", "visible": True}
file_24_0_QModelIndex = {"column": 0, "container": address_Book_MyAddresses_adr_File_QTableWidget, "row": 24, "type": "QModelIndex"}
qt_Widget_Sample_QWidget = {"type": "QWidget", "unnamed": 1, "visible": 1, "windowTitle": "Qt Widget Sample"}
qt_Widget_Sample_ScrollRightButton_QToolButton = {"name": "ScrollRightButton", "type": "QToolButton", "visible": 1, "window": qt_Widget_Sample_QWidget}
qt_Widget_Sample_QTabWidget = {"type": "QTabWidget", "unnamed": 1, "visible": 1, "window": qt_Widget_Sample_QWidget}
qt_Widget_Sample_qt_tabwidget_tabbar_QTabBar = {"name": "qt_tabwidget_tabbar", "type": "QTabBar", "visible": 1, "window": qt_Widget_Sample_QWidget}
qt_tabwidget_tabbar_Combobox_TabItem = {"container": qt_Widget_Sample_qt_tabwidget_tabbar_QTabBar, "text": "Combobox", "type": "TabItem"}
qt_Widget_Sample_qt_tabwidget_stackedwidget_QStackedWidget = {"name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1, "window": qt_Widget_Sample_QWidget}
qt_tabwidget_stackedwidget_WidgetDemoPage = {"container": qt_Widget_Sample_qt_tabwidget_stackedwidget_QStackedWidget, "type": "WidgetDemoPage", "unnamed": 1, "visible": 1}
scrollable_Buttons_QMainWindow = {"type": "QMainWindow", "unnamed": 1, "visible": 1, "windowTitle": "Scrollable Buttons"}
scrollable_Buttons_Button_2_QPushButton = {"text": "Button 2", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": scrollable_Buttons_QMainWindow}
scrollable_Buttons_Button_5_QPushButton = {"text": "Button 5", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": scrollable_Buttons_QMainWindow}
file_QScrollBar = {"container": address_Book_MyAddresses_adr_File_QTableWidget, "type": "QScrollBar", "unnamed": 1, "visible": 1}
o30_HeaderViewItem = {"container": file_QHeaderView, "text": 30, "type": "HeaderViewItem", "visible": True}
item_Views_MainWindow = {"type": "MainWindow", "unnamed": 1, "visible": 1, "windowTitle": "Item Views"}
item_Views_qt_splithandle_QSplitterHandle = {"name": "qt_splithandle_", "occurrence": 2, "type": "QSplitterHandle", "visible": 1, "window": item_Views_MainWindow}
item_Views_qt_splithandle_QTableWidget = {"aboveWidget": item_Views_qt_splithandle_QSplitterHandle, "type": "QTableWidget", "unnamed": 1, "visible": 1, "window": item_Views_MainWindow}
qt_splithandle_QHeaderView = {"container": item_Views_qt_splithandle_QTableWidget, "orientation": 1, "type": "QHeaderView", "unnamed": 1, "visible": 1}
five_HeaderViewItem = {"container": qt_splithandle_QHeaderView, "text": "Five", "type": "HeaderViewItem", "visible": True}
assemblies_QQuickApplicationWindow = {"title": "Assemblies", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
assemblies_ScrollView = {"container": assemblies_QQuickApplicationWindow, "type": "ScrollView", "unnamed": 1, "visible": True}
o_Flickable = {"container": assemblies_ScrollView, "type": "Flickable", "unnamed": 1, "visible": True}
another_Item_Button = {"checkable": False, "container": assemblies_ScrollView, "text": "Another Item", "type": "Button", "unnamed": 1, "visible": True}
coin_system_Button = {"checkable": False, "container": assemblies_ScrollView, "text": "Coin system", "type": "Button", "unnamed": 1, "visible": True}
extra_Item_Button = {"checkable": False, "container": assemblies_ScrollView, "text": "Extra Item", "type": "Button", "unnamed": 1, "visible": True}
address_Book_Unnamed_QStatusBar = {"type": "QStatusBar", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
calculationsListView_ListView = {"container": o_QQuickWindowQmlImpl, "id": "calculationsListView", "type": "ListView", "unnamed": 1, "visible": True}
digitalOutputsListView_ListView = {"container": o_QQuickWindowQmlImpl, "objectName": "digitalOutputsListView", "type": "ListView", "visible": True}
digitalOutputsListView_delegate_0_Text = {"container": digitalOutputsListView_ListView, "index": 0, "objectName": "delegate_0", "type": "Text", "visible": True}
digitalOutputsListView_delegate_1_Text = {"container": digitalOutputsListView_ListView, "index": 1, "objectName": "delegate_1", "type": "Text", "visible": True}
file_0_0_QModelIndex = {"column": 0, "container": address_Book_Unnamed_File_QTableWidget, "row": 0, "type": "QModelIndex"}
file_QHeaderView_4 = {"container": address_Book_Unnamed_File_QTableWidget, "orientation": 2, "type": "QHeaderView", "unnamed": 1, "visible": 1}
o1_HeaderViewItem_2 = {"container": file_QHeaderView_4, "text": 1, "type": "HeaderViewItem", "visible": True}
address_Book_Unnamed_Remove_QToolButton = {"text": "Remove", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
address_Book_Unnamed_Open_QToolButton = {"text": "Open", "type": "QToolButton", "unnamed": 1, "visible": 1, "window": address_Book_Unnamed_MainWindow}
mainWindow_QQuickApplicationWindow = {"name": "mainWindow", "type": "QQuickApplicationWindow", "visible": True}
mainWindow_header_ToolBar = {"container": mainWindow_QQuickApplicationWindow, "id": "header", "type": "ToolBar", "unnamed": 1, "visible": True}
header_Add_ToolButton = {"checkable": False, "container": mainWindow_header_ToolBar, "text": "Add", "type": "ToolButton", "unnamed": 1, "visible": True}
mainWindow_addViewComponent_EditView = {"container": mainWindow_QQuickApplicationWindow, "id": "addViewComponent", "type": "EditView", "unnamed": 1, "visible": True}
addViewComponent_emailAddressField_TextField = {"container": mainWindow_addViewComponent_EditView, "echoMode": 0, "id": "emailAddressField", "type": "TextField", "unnamed": 1, "visible": True}
header_Back_ToolButton = {"checkable": False, "container": mainWindow_header_ToolBar, "text": "Back", "type": "ToolButton", "unnamed": 1, "visible": True}
